# Generated by Django 4.2.16 on 2024-10-19 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackinglink_delete_usertracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trackinglink',
            name='link',
            field=models.URLField(),
        ),
    ]
